"""Draw clean pipeline route diagrams from the optimized layout result.

The script reads facility_layout.csv generated by water_plant_layout_v3.py and
reuses the main file's pipeline definitions and segment-length calculation. The
figure layer intentionally omits facility footprint rectangles so the output
focuses on routing paths, flow direction, nodes, and segment lengths.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import os
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D


def load_main_symbols():
    """Import main model symbols without printing device probe messages."""
    with contextlib.redirect_stdout(io.StringIO()):
        from water_plant_layout_v3 import (
            PIPELINE_SYSTEM,
            Facility,
            calculate_pipeline_segment,
        )

    return PIPELINE_SYSTEM, Facility, calculate_pipeline_segment


PIPELINE_SYSTEM, Facility, calculate_pipeline_segment = load_main_symbols()


SYSTEM_OFFSETS = {
    "main_water": 0.0,
    "advanced_water": 2.0,
    "sludge": -2.0,
    "backwash": 4.0,
    "chemical": -4.0,
    "power": 6.0,
}

SYSTEM_LINEWIDTH = {
    "main_water": 0.95,
    "advanced_water": 0.90,
    "sludge": 0.90,
    "backwash": 0.85,
    "chemical": 0.85,
    "power": 0.85,
}

NODE_SIZE = 16
LABEL_OFFSET = 5.8

NODE_LABEL_OFFSETS = {
    "IPS": (3, 3), "GC": (3, 3), "PS": (3, 3), "MB": (3, 4),
    "FB": (3, 4), "SB": (3, -10), "FT": (3, 4), "CWT": (3, 4),
    "PH1": (3, 3), "PH2": (3, 4), "BWT": (3, 4), "OZG": (3, 4),
    "OZR": (3, 4), "ACF": (3, 4), "CLS": (3, 4), "CST": (3, 4),
    "CDR": (3, 4), "STK": (3, 4), "SDR": (3, 4), "SYD": (3, 4),
    "PDR": (3, 4), "TRF": (3, 4),
}

SEGMENT_LABEL_NUDGES = {
    ("main_water", "IPS", "GC"): (0.0, -1.2),
    ("main_water", "GC", "PS"): (0.0, -1.2),
    ("main_water", "PS", "MB"): (0.0, -1.2),
    ("main_water", "MB", "FB"): (0.0, -1.2),
    ("main_water", "FB", "SB"): (0.0, -1.2),
    ("main_water", "SB", "FT"): (-1.8, 0.0),
    ("main_water", "FT", "CWT"): (0.0, 3.0),
    ("backwash", "CWT", "BWT"): (0.0, -2.5),
    ("backwash", "BWT", "FT"): (0.0, -2.0),
    ("chemical", "CDR", "MB"): (-2.0, 0.0),
    ("chemical", "CDR", "FB"): (0.0, -2.2),
    ("chemical", "CST", "CDR"): (-2.0, 0.0),
    ("chemical", "OZR", "OZG"): (-2.0, 0.0),
    ("chemical", "CLS", "CWT"): (-2.0, 0.0),
    ("power", "PDR", "PH1"): (0.0, -6.0),
    ("power", "TRF", "PDR"): (0.0, -2.0),
    ("power", "PDR", "PH2"): (0.0, 2.0),
}

SEGMENT_LABEL_POSITIONS = {
    ("main_water", "IPS", "GC"): (14.0, -1.5),
    ("main_water", "GC", "PS"): (28.0, -1.5),
    ("main_water", "PS", "MB"): (47.5, -1.5),
    ("main_water", "MB", "FB"): (65.0, 5.0),
    ("main_water", "FB", "SB"): (82.0, 3.0),
    ("main_water", "SB", "FT"): (91.5, 18.0),
    ("main_water", "FT", "CWT"): (111.0, 35.0),
    ("main_water", "CWT", "PH2"): (142.0, 42.0),
    ("advanced_water", "FT", "OZG"): (86.0, 39.0),
    ("advanced_water", "OZG", "ACF"): (85.5, 57.0),
    ("advanced_water", "ACF", "CWT"): (111.0, 54.0),
    ("sludge", "SB", "STK"): (116.0, 4.3),
    ("sludge", "STK", "SDR"): (133.0, 4.5),
    ("sludge", "SDR", "SYD"): (149.0, 4.5),
    ("backwash", "CWT", "BWT"): (108.0, 27.0),
    ("backwash", "BWT", "FT"): (84.5, 35.0),
    ("chemical", "CST", "CDR"): (52.5, 39.5),
    ("chemical", "CDR", "MB"): (51.5, 24.5),
    ("chemical", "CDR", "FB"): (73.0, 22.0),
    ("chemical", "CLS", "CWT"): (128.0, 52.0),
    ("chemical", "OZR", "OZG"): (72.5, 57.0),
    ("power", "PDR", "PH1"): (90.0, -7.0),
    ("power", "PDR", "PH2"): (156.0, 39.0),
    ("power", "TRF", "PDR"): (171.5, 26.0),
}


DISPLAY_ROUTE_LANES = {
    ("power", "PDR", "PH1"): {"axis": "y", "lane": -3.0},
    ("power", "PDR", "PH2"): {"axis": "y", "lane": 37.0},
    ("power", "TRF", "PDR"): {"axis": "y", "lane": 28.0},
    ("backwash", "CWT", "BWT"): {"axis": "x", "lane": 104.5, "via": [(104.5, 36.5)]},
    ("backwash", "BWT", "FT"): {"axis": "y", "lane": 34.0},
    ("chemical", "CDR", "MB"): {"axis": "x", "lane": 57.5},
    ("chemical", "CDR", "FB"): {"axis": "y", "lane": 17.5},
}

PIPE_LABEL_EN = {
    "main_water": "Main water",
    "advanced_water": "Advanced treatment",
    "sludge": "Sludge",
    "backwash": "Backwash",
    "chemical": "Chemical dosing",
    "power": "Power cable",
}


def apply_style():
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans", "Microsoft YaHei", "SimHei"],
        "svg.fonttype": "none",
        "pdf.fonttype": 42,
        "axes.unicode_minus": False,
        "font.size": 7,
        "axes.labelsize": 7,
        "xtick.labelsize": 6,
        "ytick.labelsize": 6,
        "axes.linewidth": 0.65,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
    })


def read_layout(layout_csv: str) -> dict[str, Facility]:
    df = pd.read_csv(layout_csv)
    required = {"code", "name_cn", "zone", "x_m", "y_m", "width_m", "height_m", "safety_level"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"facility_layout.csv is missing columns: {', '.join(sorted(missing))}")

    facilities = {}
    for _, row in df.iterrows():
        width = float(row["width_m"])
        height = float(row["height_m"])
        facility = Facility(
            str(row["code"]),
            str(row["name_cn"]),
            width,
            height,
            str(row["zone"]),
            int(row["safety_level"]),
        )
        facility.x = float(row["x_m"])
        facility.y = float(row["y_m"])
        facility.rotated = False
        facilities[facility.name] = facility
    return facilities


def facility_dims(facility: Facility) -> tuple[float, float]:
    return facility.get_dimensions()


def center(facility: Facility) -> tuple[float, float]:
    width, height = facility_dims(facility)
    return facility.x + width / 2, facility.y + height / 2


def orthogonal_route(start: Facility, end: Facility, system_name: str) -> list[tuple[float, float]]:
    """Draw a schematic orthogonal pipe route between visible facility nodes.

    Facility footprints are not shown in this figure, so routes must connect to
    center nodes directly. Segment lengths in the exported tables still come
    from the main model's boundary-clearance calculation.
    """
    p0 = center(start)
    p3 = center(end)
    offset = SYSTEM_OFFSETS.get(system_name, 0.0)
    dx = abs(p3[0] - p0[0])
    dy = abs(p3[1] - p0[1])

    if dx >= dy:
        mid_x = (p0[0] + p3[0]) / 2 + offset
        return [p0, (mid_x, p0[1]), (mid_x, p3[1]), p3]

    mid_y = (p0[1] + p3[1]) / 2 + offset
    return [p0, (p0[0], mid_y), (p3[0], mid_y), p3]


def route_with_lane(
    p0: tuple[float, float],
    p3: tuple[float, float],
    lane_spec: dict,
) -> list[tuple[float, float]]:
    points = [p0]
    if lane_spec["axis"] == "y":
        lane = float(lane_spec["lane"])
        points.extend([(p0[0], lane), *lane_spec.get("via", []), (p3[0], lane)])
    else:
        lane = float(lane_spec["lane"])
        points.extend([(lane, p0[1]), *lane_spec.get("via", []), (lane, p3[1])])
    points.append(p3)
    return compact_route(points)


def compact_route(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    compacted = []
    for point in points:
        if not compacted or point != compacted[-1]:
            compacted.append(point)
    return compacted


def display_route(start: Facility, end: Facility, system_name: str) -> list[tuple[float, float]]:
    p0 = center(start)
    p3 = center(end)
    lane_spec = (
        DISPLAY_ROUTE_LANES.get((system_name, start.name, end.name)) or
        DISPLAY_ROUTE_LANES.get((system_name, end.name, start.name))
    )
    if lane_spec:
        return route_with_lane(p0, p3, lane_spec)
    return orthogonal_route(start, end, system_name)


def route_midpoint(points: list[tuple[float, float]]) -> tuple[float, float]:
    lengths = []
    total = 0.0
    for p1, p2 in zip(points[:-1], points[1:]):
        length = abs(p2[0] - p1[0]) + abs(p2[1] - p1[1])
        lengths.append(length)
        total += length

    if total == 0:
        return points[0]

    target = total / 2
    acc = 0.0
    for (p1, p2), length in zip(zip(points[:-1], points[1:]), lengths):
        if acc + length >= target:
            ratio = (target - acc) / max(length, 1e-9)
            return (p1[0] + (p2[0] - p1[0]) * ratio, p1[1] + (p2[1] - p1[1]) * ratio)
        acc += length
    return points[-1]


def longest_route_leg(points: list[tuple[float, float]]) -> tuple[tuple[float, float], tuple[float, float]]:
    legs = list(zip(points[:-1], points[1:]))
    if not legs:
        return points[0], points[0]
    return max(legs, key=lambda leg: abs(leg[1][0] - leg[0][0]) + abs(leg[1][1] - leg[0][1]))


def route_label_position(
    points: list[tuple[float, float]],
    system_name: str,
    start: str,
    end: str,
) -> tuple[float, float]:
    fixed = (
        SEGMENT_LABEL_POSITIONS.get((system_name, start, end)) or
        SEGMENT_LABEL_POSITIONS.get((system_name, end, start))
    )
    if fixed is not None:
        return fixed

    p1, p2 = longest_route_leg(points)
    dx = p2[0] - p1[0]
    dy = p2[1] - p1[1]
    midpoint = ((p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2)

    if abs(dx) >= abs(dy):
        x, y = midpoint[0], midpoint[1] - LABEL_OFFSET
    else:
        x, y = midpoint[0] - LABEL_OFFSET, midpoint[1]

    nudge = (
        SEGMENT_LABEL_NUDGES.get((system_name, start, end)) or
        SEGMENT_LABEL_NUDGES.get((system_name, end, start)) or
        (0.0, 0.0)
    )
    return x + nudge[0], y + nudge[1]


def arrow_points_on_leg(
    p1: tuple[float, float],
    p2: tuple[float, float],
) -> tuple[tuple[float, float], tuple[float, float]]:
    x1, y1 = p1
    x2, y2 = p2
    return (
        (x1 + (x2 - x1) * 0.52, y1 + (y2 - y1) * 0.52),
        (x1 + (x2 - x1) * 0.78, y1 + (y2 - y1) * 0.78),
    )


def collect_route_nodes(
    facilities: dict[str, Facility],
    system_names: list[str],
) -> dict[str, tuple[float, float]]:
    nodes = {}
    samples: dict[str, list[tuple[float, float]]] = {}

    for system_name in system_names:
        for start, end in PIPELINE_SYSTEM[system_name]["pipes"]:
            if start not in facilities or end not in facilities:
                continue
            samples.setdefault(start, []).append(center(facilities[start]))
            samples.setdefault(end, []).append(center(facilities[end]))

    for label, coords in samples.items():
        nodes[label] = (
            float(np.mean([p[0] for p in coords])),
            float(np.mean([p[1] for p in coords])),
        )
    return nodes


def draw_route_nodes(ax, nodes: dict[str, tuple[float, float]]):
    if not nodes:
        return

    xs = [point[0] for point in nodes.values()]
    ys = [point[1] for point in nodes.values()]
    ax.scatter(xs, ys, s=NODE_SIZE, color="#111111", edgecolor="#111111", linewidth=0.35, zorder=7)

    for label, point in nodes.items():
        offset = NODE_LABEL_OFFSETS.get(label, (3, 3))
        annotation = ax.annotate(
            label,
            xy=point,
            xytext=offset,
            textcoords="offset points",
            fontsize=5.2,
            fontweight="bold",
            color="#222222",
            zorder=8,
        )
        annotation.set_path_effects([
            path_effects.Stroke(linewidth=1.2, foreground="white"),
            path_effects.Normal(),
        ])


def route_bounds(facilities: dict[str, Facility], system_names: list[str]) -> tuple[float, float, float, float]:
    xs = []
    ys = []

    for system_name in system_names:
        for start, end in PIPELINE_SYSTEM[system_name]["pipes"]:
            if start not in facilities or end not in facilities:
                continue
            for x, y in display_route(facilities[start], facilities[end], system_name):
                xs.append(x)
                ys.append(y)

    if not xs or not ys:
        max_x = max(f.x + facility_dims(f)[0] for f in facilities.values())
        max_y = max(f.y + facility_dims(f)[1] for f in facilities.values())
        return -3.0, max_x + 3.0, -3.0, max_y + 3.0

    return min(xs), max(xs), min(ys), max(ys)


def padded_equal_bounds(
    xmin: float,
    xmax: float,
    ymin: float,
    ymax: float,
    pad: float = 8.0,
    min_span: float = 22.0,
) -> tuple[float, float, float, float]:
    xmid = (xmin + xmax) / 2
    ymid = (ymin + ymax) / 2
    span = max(xmax - xmin, ymax - ymin, min_span) + pad * 2
    half = span / 2
    return xmid - half, xmid + half, ymid - half, ymid + half


def padded_bounds(
    xmin: float,
    xmax: float,
    ymin: float,
    ymax: float,
    pad_x: float = 5.0,
    pad_y: float = 4.0,
) -> tuple[float, float, float, float]:
    return xmin - pad_x, xmax + pad_x, ymin - pad_y, ymax + pad_y


def draw_pipeline_system(
    ax,
    facilities: dict[str, Facility],
    system_name: str,
    annotate: bool = True,
) -> list[dict]:
    rows = []
    system = PIPELINE_SYSTEM[system_name]
    color = system["color"]
    linestyle = "-"
    linewidth = SYSTEM_LINEWIDTH.get(system_name, 1.6)

    for start, end in system["pipes"]:
        if start not in facilities or end not in facilities:
            continue

        points = display_route(facilities[start], facilities[end], system_name)
        xs = [p[0] for p in points]
        ys = [p[1] for p in points]
        ax.plot(
            xs,
            ys,
            color=color,
            lw=linewidth,
            linestyle=linestyle,
            solid_capstyle="round",
            solid_joinstyle="round",
            alpha=0.96,
            zorder=4,
        )

        p_prev, p_end = arrow_points_on_leg(*longest_route_leg(points))
        ax.annotate(
            "",
            xy=p_end,
            xytext=p_prev,
            arrowprops=dict(
                arrowstyle="->",
                lw=linewidth * 0.95,
                color=color,
                shrinkA=0,
                shrinkB=0,
                mutation_scale=6,
            ),
            zorder=5,
        )

        segment = calculate_pipeline_segment(facilities[start], facilities[end], system_name)
        mid = route_label_position(points, system_name, start, end)
        if annotate:
            text = ax.text(
                mid[0],
                mid[1],
                f"{segment['routed_length_m']:.1f} m",
                ha="center",
                va="center",
                fontsize=4.8,
                color="#111111",
                zorder=6,
            )
            text.set_path_effects([
                path_effects.Stroke(linewidth=1.0, foreground="white"),
                path_effects.Normal(),
            ])

        rows.append({
            "system": system_name,
            "label": system.get("label", system_name),
            "label_en": PIPE_LABEL_EN.get(system_name, system_name),
            "from": start,
            "to": end,
            "routed_length_m": round(segment["routed_length_m"], 3),
            "weighted_length_m": round(segment["weighted_length_m"], 3),
            "center_manhattan_m": round(segment["center_manhattan_m"], 3),
            "edge_clearance_m": round(segment["edge_clearance_m"], 3),
        })
    return rows


def setup_axes(
    ax,
    facilities: dict[str, Facility],
    title: str,
    system_names: list[str] | None = None,
    equal_padding: bool = True,
    pad_x: float = 5.0,
    pad_y: float = 4.0,
    aspect: str = "equal",
):
    if system_names is None:
        max_x = max(f.x + facility_dims(f)[0] for f in facilities.values())
        max_y = max(f.y + facility_dims(f)[1] for f in facilities.values())
        xmin, xmax, ymin, ymax = -3.0, max_x + 3.0, -3.0, max_y + 3.0
    else:
        bounds = route_bounds(facilities, system_names)
        if equal_padding:
            xmin, xmax, ymin, ymax = padded_equal_bounds(*bounds)
        else:
            xmin, xmax, ymin, ymax = padded_bounds(*bounds, pad_x=pad_x, pad_y=pad_y)
        max_x = xmax
        max_y = ymax

    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, ymax)
    ax.set_aspect(aspect)
    ax.set_title(title, loc="left", fontsize=9, fontweight="bold", pad=5)
    ax.set_xlabel("x coordinate (m)", labelpad=3)
    ax.set_ylabel("y coordinate (m)", labelpad=3)

    span = min(xmax - xmin, ymax - ymin)
    step = max(5, int(round(span / 4 / 5) * 5))
    ax.set_xticks(np.arange(np.floor(xmin / step) * step, xmax + step, step))
    ax.set_yticks(np.arange(np.floor(ymin / step) * step, ymax + step, step))
    ax.grid(color="#EEEEEE", lw=0.30, zorder=0)
    ax.set_facecolor("white")


def save_figure(fig, output_base: str):
    fig.savefig(f"{output_base}.svg", bbox_inches="tight")
    fig.savefig(f"{output_base}.pdf", bbox_inches="tight")
    fig.savefig(f"{output_base}.png", dpi=300, bbox_inches="tight")


def draw_combined(facilities: dict[str, Facility], output_base: str) -> pd.DataFrame:
    fig, ax = plt.subplots(figsize=(300 / 25.4, 145 / 25.4), dpi=180)
    system_names = list(PIPELINE_SYSTEM.keys())
    setup_axes(
        ax,
        facilities,
        "Pipeline routing network derived from optimized layout",
        system_names,
        equal_padding=False,
        pad_x=4.0,
        pad_y=3.5,
    )

    rows = []
    for system_name in system_names:
        rows.extend(draw_pipeline_system(ax, facilities, system_name, annotate=True))

    draw_route_nodes(ax, collect_route_nodes(facilities, system_names))

    legend_handles = [
        Line2D(
            [0],
            [0],
            color=info["color"],
            lw=SYSTEM_LINEWIDTH.get(name, 1.6),
            linestyle="-",
            label=PIPE_LABEL_EN.get(name, name),
        )
        for name, info in PIPELINE_SYSTEM.items()
    ]
    ax.legend(
        handles=legend_handles,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.28),
        ncol=6,
        handlelength=2.4,
        columnspacing=1.4,
        handletextpad=0.5,
        fontsize=7.2,
    )

    fig.subplots_adjust(left=0.055, right=0.995, top=0.91, bottom=0.21)
    save_figure(fig, f"{output_base}_combined")
    plt.close(fig)
    return pd.DataFrame(rows)


def draw_system_panels(facilities: dict[str, Facility], output_base: str):
    systems = list(PIPELINE_SYSTEM.keys())
    fig, axes = plt.subplots(2, 3, figsize=(260 / 25.4, 165 / 25.4), dpi=170, constrained_layout=True)

    for index, (ax, system_name) in enumerate(zip(axes.flat, systems)):
        setup_axes(
            ax,
            facilities,
            PIPE_LABEL_EN.get(system_name, system_name),
            [system_name],
            equal_padding=False,
            pad_x=5.0,
            pad_y=4.0,
            aspect="auto",
        )
        row, col = divmod(index, 3)
        if row == 0:
            ax.set_xlabel("")
        if col != 0:
            ax.set_ylabel("")
        draw_pipeline_system(ax, facilities, system_name, annotate=True)
        draw_route_nodes(ax, collect_route_nodes(facilities, [system_name]))

    for ax in axes.flat[len(systems):]:
        ax.axis("off")

    fig.suptitle("Pipeline systems by category", fontsize=9, fontweight="bold")
    save_figure(fig, f"{output_base}_systems")
    plt.close(fig)


def find_latest_layout_csv() -> str:
    candidates = sorted(
        Path("outputs").glob("**/facility_layout.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        raise FileNotFoundError(
            "No outputs/**/facility_layout.csv found. Run the main optimizer first or pass --layout-csv."
        )
    return str(candidates[0])


def main():
    parser = argparse.ArgumentParser(description="Draw pipeline routes from the main optimized layout result.")
    parser.add_argument("--layout-csv", default=None, help="facility_layout.csv generated by the main optimizer")
    parser.add_argument("--output-dir", default=None, help="Output directory")
    parser.add_argument("--basename", default="pipeline_routing", help="Output filename prefix")
    args = parser.parse_args()

    layout_csv = args.layout_csv or find_latest_layout_csv()
    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = os.path.join(os.path.dirname(layout_csv), "pipeline_drawings")
    os.makedirs(output_dir, exist_ok=True)

    apply_style()
    facilities = read_layout(layout_csv)
    output_base = os.path.join(output_dir, args.basename)
    df_segments = draw_combined(facilities, output_base)
    draw_system_panels(facilities, output_base)

    segment_csv = os.path.join(output_dir, f"{args.basename}_segments.csv")
    summary_csv = os.path.join(output_dir, f"{args.basename}_summary.csv")
    df_segments.to_csv(segment_csv, index=False, encoding="utf-8-sig")
    if not df_segments.empty:
        summary = (
            df_segments.groupby(["system", "label", "label_en"], as_index=False)
            .agg(
                segment_count=("from", "count"),
                routed_length_m=("routed_length_m", "sum"),
                weighted_length_m=("weighted_length_m", "sum"),
            )
        )
        summary.to_csv(summary_csv, index=False, encoding="utf-8-sig")

    print("Pipeline drawing completed:")
    print(f"  Layout source: {layout_csv}")
    print(f"  Combined route figure: {output_base}_combined.svg/.pdf/.png")
    print(f"  System route panels: {output_base}_systems.svg/.pdf/.png")
    print(f"  Segment table: {segment_csv}")
    if os.path.exists(summary_csv):
        print(f"  System summary: {summary_csv}")


if __name__ == "__main__":
    main()
